query CartInput {
  shop {
    localTime {
      date
    }
  }
  cart {
    lines {
      id
      quantity
      merchandise {
        __typename
        ... on ProductVariant {
          title
          product {
            title
            productType
          }
        }
      }
      cost {
        amountPerQuantity {
          amount
        }
      }
      dateAttribute: attribute(key: "date") {
        value
      }
      daynameAttribute: attribute(key: "day") {
        value
      }
      immediateInventoryAttribute: attribute(key: "immediate_inventory") {
        value
      }
    }
    buyerIdentity {
      customer {
        id
        email
        loyaltyStatus: metafield(namespace: "loyalty", key: "status") {
          value
        }
        loyaltyFreeItems: metafield(namespace: "loyalty", key: "free_items") {
          value
        }
        customLoyaltyStatus: metafield(namespace: "custom", key: "loyalty_status") {
          value
        }
        customLoyaltyFreeItems: metafield(namespace: "custom", key: "loyalty_free_items") {
          value
        }
      }
    }
  }
  discount {
    discountClasses
  }
}
