# Learn more about configuring your checkout UI extension:
# https://shopify.dev/api/checkout-extensions/checkout/configuration

# The version of APIs your extension will receive. Learn more:
# https://shopify.dev/docs/api/usage/versioning
api_version = "2025-04"

# Top-level capabilities (should apply to all extensions unless overridden)
[capabilities]
api_access = true
network_access = true

[[extensions]]
name = "checkout-ui-thank-you"
handle = "checkout-ui-thank-you"
type = "ui_extension"
# Capabilities for thank-you extension (inherits from top-level if not specified here)
# If specific overrides were needed, they would go here like:
# [extensions.capabilities]
# network_access = true 

[[extensions.targeting]]
module = "./src/index.js"
target = "purchase.thank-you.block.render"
export = "thankYouExtension"

[[extensions]]
name = "checkout-ui-order-status"
handle = "checkout-ui-order-status"
type = "ui_extension"
# Explicitly define capabilities for the order-status extension
[extensions.capabilities] # This defines capabilities specifically for this [[extensions]] block
api_access = true       # Keeping api_access as well, though network_access is the one from error
network_access = true

[[extensions.targeting]]
module = "./src/index.js"
target = "customer-account.order-status.block.render"
export = "orderStatusExtension"

# Loads metafields on checkout resources, including the cart,
# products, customers, and more. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#metafields

# [[extensions.metafields]]
# namespace = "my_namespace"
# key = "my_key"
# [[extensions.metafields]]
# namespace = "my_namespace"
# key = "my_other_key"

# Defines settings that will be collected from merchants installing
# your extension. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#settings-definition

# [extensions.settings]
# [[extensions.settings.fields]]
# key = "banner_title"
# type = "single_line_text_field"
# name = "Banner title"
# description = "Enter a title for the banner"
