persistence true
persistence_location /mosquitto/data/
persistence_file mosquitto.db
autosave_interval 30

log_dest stdout
log_dest file /mosquitto/log/mosquitto.log
log_dest topic
log_timestamp true
log_type error
log_type warning
log_type notice
log_type information

sys_interval 30
connection_messages true

include_dir /mosquitto/config/conf.d
