"""Replay the cheap half of the review pipeline locally, in seconds.

WHY THIS EXISTS
---------------
A full Kaggle pass costs 90 minutes to 4 hours, and until now every filter
tweak — a threshold, a size bound, an arbitration rule — needed one of those
runs to evaluate. That is the wrong unit of iteration: a wrong guess about a
number should cost seconds, not an afternoon.

The review pipeline has a clean seam. Above it, proposals are generated by
YOLOE text prompts, YOLOE visual prompts and SAM 3.1 — GPU work, ~4.5 minutes
per image. Below it, everything is arithmetic on boxes that already exist:

    reflection filter -> kraft-ruler filter -> packet plausibility
      -> cross-class arbitration -> exact-count trim -> detector validator

`assisted_label_review.py --raw-proposal-dump DIR` persists the union at that
seam. This script reads that dump, replays the whole downstream half with the
CURRENT code, and prints the gate. Same functions the Kaggle run uses, imported
from the same file, so a result here is not an approximation of the real thing —
it is the real thing, minus the part that needs a GPU.

USE IT FOR: filter thresholds, size bounds, arbitration rules, scoring policy.
NOT FOR: anything that changes what gets proposed — prompts, checkpoints,
tiling, confidence floors. Those live above the seam and still need Kaggle.
"""

from __future__ import annotations

import argparse
import importlib.util
import json
import sys
from pathlib import Path
from typing import Any

REPO = Path(__file__).resolve().parent.parent
RUNTIME = REPO / "training/autoresearch/kaggle_label_factory/assisted_label_review.py"


def load_runtime():
    """Import the Kaggle runtime so the replay uses the exact shipped logic."""
    spec = importlib.util.spec_from_file_location("assisted_label_review_replay", RUNTIME)
    module = importlib.util.module_from_spec(spec)
    sys.modules["assisted_label_review_replay"] = module
    assert spec.loader is not None
    spec.loader.exec_module(module)
    return module


def replay_image(module, payload: dict[str, Any], image_path: Path) -> dict[str, Any]:
    """Run one image's proposals through every post-detection stage."""
    from PIL import Image, ImageOps

    instances = [dict(row) for row in payload["instances"]]
    width = int(payload["image_width"])
    is_reference = bool(payload.get("is_audited_reference"))
    stages: dict[str, int] = {"raw": len(instances)}

    # Audited reference images carry the reviewer's own immutable rectangles and
    # are deliberately exempt from every filter, exactly as in the real run.
    if not is_reference:
        with Image.open(image_path) as raw:
            oriented = ImageOps.exif_transpose(raw).convert("RGB")

        instances, _ = module.filter_fridge_door_reflection_instances(image_path, instances)
        stages["after_reflection"] = len(instances)

        if hasattr(module, "filter_adjacent_cabinet_instances"):
            instances, _ = module.filter_adjacent_cabinet_instances(image_path, instances)
            stages["after_adjacent_cabinet"] = len(instances)

        instances, _ = module.filter_sauce_cup_stack_kraft_bowls(instances)
        stages["after_kraft_ruler"] = len(instances)

        if hasattr(module, "filter_implausible_packet_proposals"):
            instances, _ = module.filter_implausible_packet_proposals(instances, width)
            stages["after_packet_plausibility"] = len(instances)

        instances, _ = module.drop_cross_class_duplicate_proposals(instances, oriented)
        stages["after_cross_class"] = len(instances)

    return {"instances": instances, "stages": stages}


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("raw_dump_dir", type=Path,
                        help="Directory written by --raw-proposal-dump")
    parser.add_argument("--images-dir", type=Path,
                        default=REPO / "training/sam_annotation_batch/images")
    parser.add_argument("--correction-manifest", type=Path, required=True)
    parser.add_argument("--show-stages", action="store_true",
                        help="Print how many boxes each filter removed, per image.")
    args = parser.parse_args(argv)

    module = load_runtime()
    corrections = {
        row["image_name"]: row
        for row in json.loads(args.correction_manifest.read_text(encoding="utf-8"))["images"]
    }

    records: list[dict[str, Any]] = []
    for dump_path in sorted(args.raw_dump_dir.glob("*.json")):
        payload = json.loads(dump_path.read_text(encoding="utf-8"))
        image_name = payload["image_name"]
        result = replay_image(module, payload, args.images_dir / image_name)

        correction = corrections.get(image_name, {})
        trimmed, _ = module.enforce_exact_human_estimate_counts(
            result["instances"], correction
        )
        counts = {name: 0 for name in module.FIXED_CLASS_NAMES}
        for row in trimmed:
            class_id = int(row["class_id"])
            if 0 <= class_id < len(module.FIXED_CLASS_NAMES):
                counts[module.FIXED_CLASS_NAMES[class_id]] += 1
        records.append({"image_name": image_name, "final_class_counts": counts})

        if args.show_stages:
            stages = " -> ".join(f"{k}:{v}" for k, v in result["stages"].items())
            print(f"  {image_name[:30]:<32}{stages}")

    report = module.run_detector_validator_agent(
        records, corrections,
        minimum_accuracy=module.DETECTOR_VALIDATOR_MIN_ACCURACY,
        expected_image_count=20,
    )
    for row in report["images"]:
        if not row.get("scored"):
            continue
        status = "PASS" if row["passed"] else "fail"
        print(f"{str(row['image_name'])[:34]:<36}{status}")
        for reason in row.get("mismatches") or []:
            print(f"      {reason}")
    print()
    print(f"accuracy={report['required_item_count_accuracy']:.4f} "
          f"scored={report['scored_image_count']} "
          f"passed={report['passed_image_count']} "
          f"handoff={report['human_handoff_allowed']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
